[project]
requires-python = ">= 3.11"

[tool.black]
line-length = 120
extend-exclude = "HIE|PersuasionNLPTools|data"

[tool.isort]
profile = "black"
line_length = 120
extend_skip = ["HIE", "PersuasionNLPTools", "data"]